Copyright (c) Microsoft Corporation. All rights reserved.

Licensed under the MIT License.

## Abstractive Summarization on CNN/DM Dataset using Transformers


### Summary

This notebook demonstrates how to fine tune Transformers for extractive text summarization. Utility functions and classes in the NLP Best Practices repo are used to facilitate data preprocessing, model training, model scoring, result postprocessing, and model evaluation.




### Before You Start

The running time shown in this notebook is on a Standard_NC24s_v3 Azure Ubuntu Virtual Machine with 4 NVIDIA Tesla V100 GPUs. 
> **Tip**: If you want to run through the notebook quickly, you can set the **`QUICK_RUN`** flag in the cell below to **`True`** to run the notebook on a small subset of the data and a smaller number of epochs. 

Using only 1 NVIDIA Tesla V100 GPUs, 16GB GPU memory configuration,
- for data preprocessing, it takes around 1 minutes to preprocess the data for quick run. Otherwise it takes ~20 minutes to finish the data preprocessing. This time estimation assumes that the chosen transformer model is "distilbert-base-uncased" and the sentence selection method is "greedy", which is the default. The preprocessing time can be significantly longer if the sentence selection method is "combination", which can achieve better model performance.

- for model fine tuning, it takes around 2 minutes for quick run. Otherwise, it takes around ~3 hours to finish. This estimation assumes the chosen encoder method is "transformer". The model fine tuning time can be shorter if other encoder method is chosen, which may result in worse model performance. 

### Additional Notes

* **ROUGE Evalation**: To run rouge evaluation, please refer to the section of compute_rouge_perl in [summarization_evaluation.ipynb](./summarization_evaluation.ipynb) for setup.

* **Distributed Training**:
Please note that the jupyter notebook only allows to use pytorch [DataParallel](https://pytorch.org/docs/master/nn.html#dataparallel). Faster speed and larger batch size can be achieved with pytorch [DistributedDataParallel](https://pytorch.org/docs/master/notes/ddp.html)(DDP). Script [extractive_summarization_cnndm_distributed_train.py](./extractive_summarization_cnndm_distributed_train.py) shows an example of how to use DDP.



In [1]:
%load_ext autoreload

%autoreload 2
## Set QUICK_RUN = True to run the notebook on a small subset of data and a smaller number of epochs.
QUICK_RUN = True


### Configuration


In [2]:
import os
import shutil
import sys
from tempfile import TemporaryDirectory
import torch

nlp_path = os.path.abspath("../../")
if nlp_path not in sys.path:
    sys.path.insert(0, nlp_path)

from utils_nlp.dataset.cnndm import CNNDMBertSumProcessedData, CNNDMSummarizationDataset
from utils_nlp.eval import compute_rouge_python, compute_rouge_perl
from utils_nlp.models.transformers.abstractive_summarization_bartt5 import AbstractiveSummarizer, SummarizationProcessor

from utils_nlp.models.transformers.datasets import SummarizationDataset
import nltk
from nltk import tokenize

import pandas as pd
import scrapbook as sb
import pprint

/home/daden/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/daden/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/daden/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/daden/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:519: Futu


### Configuration: choose the transformer model to be used

Several pretrained models have been made available by [Hugging Face](https://github.com/huggingface/transformers). For extractive summarization, the following pretrained models are supported. 

In [3]:
#pd.DataFrame({"model_name": ExtractiveSummarizer.list_supported_models()})

In [4]:
# Transformer model being used
MODEL_NAME = "t5-large"

In [5]:
# notebook parameters
# the cache data path during find tuning
CACHE_DIR = TemporaryDirectory().name
        
processor = SummarizationProcessor(MODEL_NAME,cache_dir=CACHE_DIR ) #tokenizer, config.prefix)

### Data Preprocessing

The dataset we used for this notebook is CNN/DM dataset which contains the documents and accompanying questions from the news articles of CNN and Daily mail. The highlights in each article are used as summary. The dataset consits of ~289K training examples, ~11K valiation examples and ~11K test examples.   The code in following cell will download the CNN/DM dataset listed at https://github.com/harvardnlp/sent-summary/.


In [6]:
# the data path used to save the downloaded data file
DATA_PATH = TemporaryDirectory().name
# The number of lines at the head of data file used for preprocessing. -1 means all the lines.
TOP_N = 1000
if not QUICK_RUN:
    TOP_N = -1

In [7]:
train_dataset, test_dataset = CNNDMSummarizationDataset(top_n=TOP_N, local_cache_path=DATA_PATH, raw=True)

100%|██████████| 489k/489k [00:07<00:00, 63.4kKB/s] 


Preprocess the data.

In [8]:

abs_sum_train = processor.preprocess(train_dataset)
abs_sum_test = processor.preprocess(test_dataset)


In [9]:
"""
# save and load preprocessed data
save_path = os.path.join(DATA_PATH, "processed")
torch.save(ext_sum_train, os.path.join(save_path, "train_full.pt"))
torch.save(ext_sum_test, os.path.join(save_path, "test_full.pt"))

"""
# ext_sum_train = torch.load(os.path.join(save_path, "train_full.pt"))
# ext_sum_test = torch.load(os.path.join(save_path, "test_full.pt"))

'\n# save and load preprocessed data\nsave_path = os.path.join(DATA_PATH, "processed")\ntorch.save(ext_sum_train, os.path.join(save_path, "train_full.pt"))\ntorch.save(ext_sum_test, os.path.join(save_path, "test_full.pt"))\n\n'

In [10]:
print(len(abs_sum_train))
print(len(abs_sum_test))

1000
1000


#### Inspect Data

In [11]:
abs_sum_train[0].keys()

dict_keys(['src', 'src_txt', 'tgt', 'tgt_txt', 'source_ids', 'source_mask', 'target_ids'])

In [12]:
abs_sum_train[0]

{'src': "editor 's note : in our behind the scenes series , cnn correspondents share their experiences in covering news and analyze the stories behind the events . here , soledad o'brien takes users inside a jail where many of the inmates are mentally ill . an inmate housed on the `` forgotten floor , '' where many mentally ill inmates are housed in miami before trial . miami , florida -lrb- cnn -rrb- -- the ninth floor of the miami-dade pretrial detention facility is dubbed the `` forgotten floor . '' here , inmates with the most severe mental illnesses are incarcerated until they 're ready to appear in court . most often , they face drug charges or charges of assaulting an officer -- charges that judge steven leifman says are usually `` avoidable felonies . '' he says the arrests often result from confrontations with police . mentally ill people often wo n't do what they 're told when police arrive on the scene -- confrontation seems to exacerbate their illness and they become more p

### Model training
To start model training, we need to create a instance of ExtractiveSummarizer.
#### Choose the transformer model.
Currently ExtractiveSummarizer support two models:
- distilbert-base-uncase, 
- bert-base-uncase

Potentionally, roberta-based model and xlnet can be supported but needs to be tested.
#### Choose the encoder algorithm.
There are four options:
- baseline: it used a smaller transformer model to replace the bert model and with transformer summarization layer
- classifier: it uses pretrained BERT and fine-tune BERT with **simple logistic classification** summarization layer
- transformer: it uses pretrained BERT and fine-tune BERT with **transformer** summarization layer
- RNN: it uses pretrained BERT and fine-tune BERT with **LSTM** summarization layer

In [13]:
BATCH_SIZE = 5 # batch size, unit is the number of samples
MAX_POS_LENGTH = 512

    


# GPU used for training
NUM_GPUS = torch.cuda.device_count()


# Learning rate
LEARNING_RATE=2e-3

# How often the statistics reports show up in training, unit is step.
REPORT_EVERY=100

# total number of steps for training
MAX_STEPS=1e2
# number of steps for warm up
WARMUP_STEPS=5e2
    
if not QUICK_RUN:
    MAX_STEPS=5e4
    WARMUP_STEPS=5e3
 

In [14]:
summarizer = AbstractiveSummarizer(processor, MODEL_NAME)

In [15]:
"""

summarizer.fit(
            ext_sum_train,
            num_gpus=NUM_GPUS,
            batch_size=BATCH_SIZE,
            gradient_accumulation_steps=2,
            max_steps=MAX_STEPS,
            learning_rate=LEARNING_RATE,
            warmup_steps=WARMUP_STEPS,
            verbose=True,
            report_every=REPORT_EVERY,
            clip_grad_norm=False,
            use_preprocessed_data=USE_PREPROCSSED_DATA
        )

"""


'\n\nsummarizer.fit(\n            ext_sum_train,\n            num_gpus=NUM_GPUS,\n            batch_size=BATCH_SIZE,\n            gradient_accumulation_steps=2,\n            max_steps=MAX_STEPS,\n            learning_rate=LEARNING_RATE,\n            warmup_steps=WARMUP_STEPS,\n            verbose=True,\n            report_every=REPORT_EVERY,\n            clip_grad_norm=False,\n            use_preprocessed_data=USE_PREPROCSSED_DATA\n        )\n\n'

In [16]:
"""
summarizer.save_model(
    os.path.join(
        CACHE_DIR,
        "extsum_modelname_{0}_usepreprocess{1}_steps_{2}.pt".format(
            MODEL_NAME, USE_PREPROCSSED_DATA, MAX_STEPS
        ),
    )
)
"""


'\nsummarizer.save_model(\n    os.path.join(\n        CACHE_DIR,\n        "extsum_modelname_{0}_usepreprocess{1}_steps_{2}.pt".format(\n            MODEL_NAME, USE_PREPROCSSED_DATA, MAX_STEPS\n        ),\n    )\n)\n'

In [17]:
# for loading a previous saved model
"""
import torch
model_path = os.path.join(
        CACHE_DIR,
        "extsum_modelname_{0}_usepreprocess{1}_steps_{2}.pt".format(
            MODEL_NAME, USE_PREPROCSSED_DATA, MAX_STEPS
        ))
summarizer = ExtractiveSummarizer(processor, MODEL_NAME, ENCODER, MAX_POS_LENGTH, CACHE_DIR)
summarizer.model.load_state_dict(torch.load(model_path, map_location="cpu"))
"""

'\nimport torch\nmodel_path = os.path.join(\n        CACHE_DIR,\n        "extsum_modelname_{0}_usepreprocess{1}_steps_{2}.pt".format(\n            MODEL_NAME, USE_PREPROCSSED_DATA, MAX_STEPS\n        ))\nsummarizer = ExtractiveSummarizer(processor, MODEL_NAME, ENCODER, MAX_POS_LENGTH, CACHE_DIR)\nsummarizer.model.load_state_dict(torch.load(model_path, map_location="cpu"))\n'

### Model Evaluation

[ROUGE](https://en.wikipedia.org/wiki/ROUGE_(metric)), or Recall-Oriented Understudy for Gisting Evaluation has been commonly used for evaluating text summarization.

In [18]:
abs_sum_test[0].keys()

dict_keys(['src', 'src_txt', 'tgt', 'tgt_txt', 'source_ids', 'source_mask', 'target_ids'])

In [19]:
source = []
target = []
for i in abs_sum_test:
    source.append(i["src_txt"]) 
    target.append(i['tgt']) 

In [20]:
target[0]

"<t> marseille prosecutor says `` so far no videos were used in the crash investigation '' despite media reports . </t> <t> journalists at bild and paris match are `` very confident '' the video clip is real , an editor says . </t> <t> andreas lubitz had informed his lufthansa training school of an episode of severe depression , airline says . </t>\n"

In [28]:

%%time
prediction = summarizer.predict(abs_sum_test[0:20], num_gpus=NUM_GPUS, batch_size=8) 




Generating summary:   0%|          | 0/3 [00:00<?, ?it/s]

dataset length is 20
tensor([[    0,   183,    29,   222,    63,  1038,    31,     7,  2041,   934,
         10173,     7,     8,   169,    13,   538,    18,     7,   152,  4985,
            15,    26,  9357,    38,     3,     9,  4930,    23,  3268,  3613,
           640,     8,  7895,     3,     5,    44,   709,  1640,   940,   151,
           130, 13763,   300,     8,   296,    16,  1412,     3,     5,    44,
           709,  3547,   591,  3539,   151, 13448,    33,  5899,    12,    43,
           118, 14014,     8,  7142,     3,     5,     1],
        [    0,   183,    29,   222,    63,  1038, 10375,  2041,  1132,    13,
          1687, 10736,  4388,     3,     5,  1687, 16513,    95,  2899,  1454,
            30,  1767,   215,     6,  3323,   250,    13,     3, 16864,   343,
           152,     3,     5,  1440,   338,  1687, 10736,    12,  8000,  5447,
            11,     3, 14389,    33,    20,   565,    23,  3745,  1452,     3,
             5,     1,     0,     0,     0,     0, 




Generating summary:  33%|███▎      | 1/3 [00:17<00:34, 17.37s/it]

tensor([[    0,   874, 10211,     7,   113,   130, 18259,    21,   386,  1274,
            44,    46,     3,    32,    51,     9,  1024,  2833,    43,   118,
          1883,     3,     5,    80,    13,     8,   874,   141,     3,     9,
           842,    18,  3897,   962,    30,     3,     7,  6010,  1135,    11,
            65,   118, 12445,    26,    68,    65,     3,    29,    31,    17,
           646,     8,   616,     3,     5,    79,   130,  6666,    12,     3,
            15,  4243,     9,    16,   108, 16841,    90,   782,    16, 10556,
             3,     5,     1,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0],
        [    0,    11,    60,   210,   129,    17,    63,     6, 10635,     6,
            47,   435,  3654,    16,   112, 10381, 11831,    15,     7,   234,
             3,     5,     8,  4301,   106,    49,    31,     7, 17413,  4193,
            19,   132,    47,   150, 16704,   577,  1381,    16,     8,  1687,
            13,   129




Generating summary:  67%|██████▋   | 2/3 [00:33<00:17, 17.03s/it]

tensor([[    0,     3, 24063,  3977,    16,     3,  5326, 18247,  2038,   227,
             3,     9, 12061,    63,   443,  8420,     3,     5,     8,  1576,
            13,     3,     2,  4223,  2936,   489,     3,    31,    31,    30,
          9030,  1135,   704,  2675,     8,  1004,    12,  1423,  1636,    11,
          3673, 20214,    15,   541,  1636,     8,   388,    24,    78,   186,
            43,     3, 24266,    38,    80,    13,     8,  1245,     7,    17,
          3413,    16,     3,   107, 30322,     3,     5,     1]],
       device='cuda:3')
tensor([[    0,     3, 20068,    15,   158,  3772,  3814,     3,     9,  4761,
          4333,   973,   336,   471,    24,  9540,     8,  1365,    12,  9192,
           257,   581, 16998,     7,    11,   110, 12032,     7,     3,     5,
           158,  3772,    10,     3,    31,    23, 27539,   120,     3, 20964,
            48,   773,    13,   223,  8058,     3,     5,     3,    31,    31,
         12137,    19,   150,   194,    




Generating summary: 100%|██████████| 3/3 [00:48<00:00, 16.36s/it]

CPU times: user 1min 22s, sys: 23.7 s, total: 1min 46s
Wall time: 50.1 s


In [25]:
a = torch.tensor([[    0,  8113, 15955,     3,     6,  2515,   663,     3,    18,     3,
            75,    29,    29,     3,    18,     8, 20609, 23489,   127,  1374,
            46,  4962,   139,     8,  8420,    13, 13692,  3108,     7,  3777,
         11923,  1828,    16, 15777,    62,    26,  1496,  1135,    24,     3,
            88,    47,    59,  2718,    13,   136,   671, 13420,    45,    30,
          1476,     8,  6112,     3,     5,  8113, 15955, 23489,   127,     3,
           115,  4920,     3,  5840,    77,  1219,     3,    75,    29,    29,
            24,     3,     2,    78,   623,   150,  3075,   130,   261,    16,
             8,  8420,  4962,     3,     5,     3,    31,    31,     3,  5840,
            77,     3,    31,     7,  2622,  1130,  3213,    57,   192, 13254,
             3,     6, 13692,  1444,     3,  9401,    11, 20609,   260,   159,
          1588,     3,     6,    13,     1],
        [    0,     8,  4727,  4991,  1938,    47,  7027,    28,     3,     9,
          7252,    44,     8,  4244,  5398,     3,     6,    16,     8,  3134,
           760,  6347,     3,     6,   213,     8,  1614,    19,     3,   390,
             3,     5,     8,  7692,   222,    77,  7137,  3814,     8,     3,
           447,    75,    31,     7, 16072,     3, 11956, 18692,    16,     3,
          7066,    76,  1208,     3,     5,    38,   724,    13,     8,  1614,
             3,     6,  7692,   222,    77,  7137,   164,    36,  1426,    12,
          3485,    18,  7993,     7,    38,   168,     3,     5,     1,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0]], device='cuda:0')

In [27]:
for i in a:
    print(i)

tensor([    0,  8113, 15955,     3,     6,  2515,   663,     3,    18,     3,
           75,    29,    29,     3,    18,     8, 20609, 23489,   127,  1374,
           46,  4962,   139,     8,  8420,    13, 13692,  3108,     7,  3777,
        11923,  1828,    16, 15777,    62,    26,  1496,  1135,    24,     3,
           88,    47,    59,  2718,    13,   136,   671, 13420,    45,    30,
         1476,     8,  6112,     3,     5,  8113, 15955, 23489,   127,     3,
          115,  4920,     3,  5840,    77,  1219,     3,    75,    29,    29,
           24,     3,     2,    78,   623,   150,  3075,   130,   261,    16,
            8,  8420,  4962,     3,     5,     3,    31,    31,     3,  5840,
           77,     3,    31,     7,  2622,  1130,  3213,    57,   192, 13254,
            3,     6, 13692,  1444,     3,  9401,    11, 20609,   260,   159,
         1588,     3,     6,    13,     1], device='cuda:0')
tensor([    0,     8,  4727,  4991,  1938,    47,  7027,    28,     3,     9,
   

In [37]:
prediction[0]

'<map object at 0x7f0bd4c62ac8>'

In [29]:
len(prediction)

20

In [30]:
prediction

["marseille , france - cnn - the french prosecutor leading an investigation into the crash of germanwings flight 9525 insisted wednesday that he was not aware of any video footage from on board the plane . marseille prosecutor brice robin told cnn that  so far no videos were used in the crash investigation . '' robin 's comments follow claims by two magazines , german daily bild and french paris match , of",
 "the formal accession was marked with a ceremony at the hague , in the netherlands , where the court is based . the palestinians signed the icc's founding rome statute in january . as members of the court , palestinians may be subject to counter-charges as well .",
 "amnesty international's annual report catalogs the use of state-sanctioned killing as a punitive measure across the globe . at least 607 people were executed around the world in 2014 . at least 2,466 people globally are confirmed to have been handed the sentence .",
 'amnesty international releases annual review of de

In [20]:
prediction

["marseille , france - cnn - the french prosecutor leading an investigation into the crash of germanwings flight 9525 insisted wednesday that he was not aware of any video footage from on board the plane . marseille prosecutor brice robin told cnn that  so far no videos were used in the crash investigation . '' robin 's comments follow claims by two magazines , german daily bild and french paris match , of",
 "the formal accession was marked with a ceremony at the hague , in the netherlands , where the court is based . the palestinians signed the icc's founding rome statute in january . as members of the court , palestinians may be subject to counter-charges as well .",
 "amnesty international's annual report catalogs the use of state-sanctioned killing as a punitive measure across the globe . at least 607 people were executed around the world in 2014 . at least 2,466 people globally are confirmed to have been handed the sentence .",
 'amnesty international releases annual review of de

In [18]:
prediction

['marseille , france - cnn - the french prosecutor leading',
 'the formal accession was marked with a ceremony at the hague , in the net',
 "amnesty international's annual report catalogs the use of state-sanction",
 'amnesty international releases annual review of death penalty worldwide . death sentences up 500%',
 'anne frank died of typhus in a nazi concentration camp at the',
 'a duke student has admitted to hanging a noose made of rope from',
 'the rev. robert h. schuller , californ',
 'the dog was hit by a car, apparently killed with a hammer and ',
 'mohammad javad zarif is the iranian foreign minister ',
 'for the first time in eight years , a tv legend returned to doing what',
 "-lrb- he 's a blue chip college basketball recruit ",
 'michele bachmann compared president obama to the co-pilot of',
 'california is a breadbasket to the nation . cali',
 "walmart's staunch criticism of a religious freedom law in its home state of ark",
 'five americans who were monitored for three 

In [43]:
prediction

['bild and paris match claim to have found a video of the crash site .',
 'palestinian authority officially became the 123rd member of the international criminal court on we',
 "amnesty international's annual report catalogs the use of state-sanction",
 '. in egypt and nigeria , courts imposed',
 'anne frank died of typhus in a nazi concentration camp at the',
 'student admitted to hanging the noose from a tree near a student union ',
 ". schuller 's legacy is a televangelist ",
 '. a dog in california , found seemingly dead after',
 'zarif is the iranian foreign minister . he has been ',
 ", he didn't seem to miss a beat . bob bark",
 '. . . . . . . . .',
 'michele bachmann compared president obama to the co-pilot of',
 '. . . . . . . . .',
 "''  the republican party will have to better stand for '' ideas",
 'of an infected person . the last of 17 patients who were being monitored are',
 'found dead in his home . he was found on his side near a bathroom',
 '. . . . . . . . ',
 ". ''we

In [55]:
prediction

['marseille , france - cnn - the french prosecutor leading',
 'the formal accession was marked with a ceremony at the hague , in the net',
 "amnesty international's annual report catalogs the use of state-sanction",
 'amnesty international releases annual review of death penalty worldwide . death sentences up 500%',
 'anne frank died of typhus in a nazi concentration camp at the',
 'a duke student has admitted to hanging a noose made of rope from',
 'the rev. robert h. schuller , californ',
 'the dog was hit by a car, apparently killed with a hammer and ',
 'mohammad javad zarif is the iranian foreign minister ',
 'for the first time in eight years , a tv legend returned to doing what',
 "-lrb- he 's a blue chip college basketball recruit ",
 'michele bachmann compared president obama to the co-pilot of',
 'california is a breadbasket to the nation . cali',
 "walmart's staunch criticism of a religious freedom law in its home state of ark",
 'five americans who were monitored for three 

In [24]:
rouge_scores = compute_rouge_python(cand=prediction, ref=target)
pprint.pprint(rouge_scores)

Number of candidates: 20
Number of references: 1000


AssertionError: 

In [ ]:
target[0]

In [ ]:
prediction[0]

In [ ]:
source[0]

In [ ]:
# for testing
sb.glue("rouge_2_f_score", rouge_scores['rouge-2']['f'])

## Prediction on a single input sample

In [ ]:
source = """
But under the new rule, set to be announced in the next 48 hours, Border Patrol agents would immediately return anyone to Mexico — without any detainment and without any due process — who attempts to cross the southwestern border between the legal ports of entry. The person would not be held for any length of time in an American facility.

Although they advised that details could change before the announcement, administration officials said the measure was needed to avert what they fear could be a systemwide outbreak of the coronavirus inside detention facilities along the border. Such an outbreak could spread quickly through the immigrant population and could infect large numbers of Border Patrol agents, leaving the southwestern border defenses weakened, the officials argued.
The Trump administration plans to immediately turn back all asylum seekers and other foreigners attempting to enter the United States from Mexico illegally, saying the nation cannot risk allowing the coronavirus to spread through detention facilities and Border Patrol agents, four administration officials said.
The administration officials said the ports of entry would remain open to American citizens, green-card holders and foreigners with proper documentation. Some foreigners would be blocked, including Europeans currently subject to earlier travel restrictions imposed by the administration. The points of entry will also be open to commercial traffic."""

In [ ]:
test_dataset = SummarizationDataset(
    None,
    source=[source],
    source_preprocessing=[tokenize.sent_tokenize],
    word_tokenize=nltk.word_tokenize,
)
processor = ExtSumProcessor(model_name=MODEL_NAME,  cache_dir=CACHE_DIR)
preprocessed_dataset = processor.preprocess(test_dataset)

In [ ]:
preprocessed_dataset[0].keys()

In [ ]:
prediction = summarizer.predict(preprocessed_dataset, num_gpus=0, batch_size=1, sentence_separator="\n")

In [ ]:
prediction

## Clean up temporary folders

In [ ]:
if os.path.exists(DATA_PATH):
    shutil.rmtree(DATA_PATH, ignore_errors=True)
if os.path.exists(CACHE_DIR):
    shutil.rmtree(CACHE_DIR, ignore_errors=True)
if USE_PREPROCSSED_DATA:
    if os.path.exists(PROCESSED_DATA_PATH):
        shutil.rmtree(PROCESSED_DATA_PATH, ignore_errors=True)